context("FisOut")

test_that("FisOut instantiation error", {
  expect_error(new(FisOut))
})
